language: node_js
node_js:
- "11"
jobs:
  include:
  - script: echo "Running unit tests (1)"
#  - script: git tag v1.0.1 && git push origin --tags && git push origin master
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
    - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
    - git push -q https://$TAGPERM@github.com/robertdumitrescu/collection-path-helper --tags
    - ls -R
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      on:
        tags: false