language: node_js
node_js:
- "11"
jobs:
  include:
  - script: echo "Running unit tests (1)"
  - script: git tag v1.0.1 && git push origin --tags && git push origin master
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      on:
        tags: true