version: 2

defaults: &defaults
#  working_directory: ~/project
  docker:
  - image: circleci/node:11.9.0

jobs:
  deploy:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Print Work Directory
        command: pwd
    - run:
        name: List
        command: ls -all
    - run:
        name: NPM install
        command: npm install
    - run:
        name: Run tests
        command: npm test
    - run:
        name: Authenticate with registry
        command: node node_modules/npm-cli-login/bin/npm-cli-login.js -u ${NPM_USERNAME} -p ${NPM_PASSWORD} -e ${NPM_EMAIL}
    - run:
        name: Publish package
        command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
#    - test
    - deploy:
        requires:
#        - test