version: 2
jobs:
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/node:11.9.0 # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run: echo "hello world" # run the `echo` command
    - run: npm install # run the `echo` command
    - run: npm run test # run the `echo` command

  publish-github-release:
    docker:
    - image: circleci/golang:1.8
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          go get github.com/tcnksm/ghr
          VERSION=$(my-binary --version)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/



workflows:
  version: 2
  default_workflow:
    jobs:
    - test
    - publish-github-release
