version: 2
jobs:
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/node:11.9.0 # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run: echo "hello world" # run the `echo` command
    - run: npm install # run the `echo` command
    - run: npm run test # run the `echo` command

  publish-github-release:
    docker:
    - image: circleci/golang:1.8
    steps:
      dependencies:
        pre:
        - go get github.com/tcnksm/ghr

      compile:
        override:
        - ant package

      deployment:
        release:
          tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
          commands:
          - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` output/



workflows:
  version: 2
  default_workflow:
    jobs:
    - test
    - publish-github-release
